### ISSUE TITLE
Discussion: Model subtraction as merge method

### ISSUE THREAD

**Issue by bmaltais** [s1dlx/sd-webui-bayesian-merger#63]
I have been thinking about how I would go about removing undesired model characteristics. One way is to dilute the model with more data that does not present the undesired characteristics... but this can be difficult... so I tought why not just subtract a model known for the undesired characteristics from the other to reduce the undesired trait.

So if you add a model to another with: `(1- alpha) * A + alpha * B` then subtracting is as simple as `(A - alpha * B) / (1 - alpha)`

I also wanted to add a strenght control as to limit how much is actually reduce. So if I only want to reduce by 25% I can set beta to 0.25 with the following code update: `(A - alpha * beta * B) / (1 - alpha * beta)`

So here is a sample of the result of running this. I attempted to reduce the "drawing" look by subtracting this model B ( https://civitai.com/models/1274/dreamlike-diffusion-10 ) from model A:

Here is a sample result:

Original prompt results:

![001-00-payload1-6 936](https://user-images.githubusercontent.com/7474674/234262695-8aa00687-0abe-4172-bbab-808e4b1d6776.png)
![001-04-payload5-6 732](https://user-images.githubusercontent.com/7474674/234262752-2d43f03b-c52a-4c70-acb6-e36cd4e6bc1b.png)

Model with drawing style subtracted with beta of 25%:

![014-00-payload1-6 722](https://user-images.githubusercontent.com/7474674/234263129-7f57f61e-110a-4c5e-8e5f-043c819eacac.png)
![014-04-payload5-6 704](https://user-images.githubusercontent.com/7474674/234263163-36a5ba8f-939f-48bd-86c0-4369d3674e81.png)

Let me know what you think and I could create a PR... also... how do I go about specifying beta via the config? Is there a parameter to use? At the moment I just hardcoded the value as 0.25.

**Comment by bmaltais** [comment]
Many thanks for the instructions. I will try to submit the PR today if time permit

**Comment by bmaltais** [comment]
Created PR: https://github.com/s1dlx/sd-webui-bayesian-merger/pull/64

**Comment by bmaltais** [comment]
I have updated the PR to solve the division by zero corner case.

**Comment by bmaltais** [comment]
I tried to restrict the range of base_beta to 0 - 0.25 like this but it does not appear to work:

```
# constant values
frozen_params:
  # block_0_alpha: 0.9           
  base_alpha: 0.5

# set ranges
custom_ranges:
  # block_1_beta: [0.1, 0.5]
  # block_2_beta: [0.4, 1.0]
  base_beta: [0, 0.25]

# group blocks
groups:
  # - [block_1_alpha, block_2_alpha, block_3_alpha]
  # - [block_3_beta, block_4_beta, base_beta]
  ```
